---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sample
  namespace: k8sample
  labels:
    app: k8sample
spec:
  selector:
    matchLabels:
      app: k8sample
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%

#    type: Recreate
  template:
    metadata:
      labels:
        app: k8sample
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
      - image: leffen/k8sample:v1.3
        imagePullPolicy: IfNotPresent
        name: k8sample
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3
