---
apiVersion: v1
kind: Service
metadata:
  name: k8sample
  namespace: k8sample
  labels:
    app: k8sample
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: k8sample