---
apiVersion: v1
kind: Service
metadata:
  name: k8sample
  namespace: k8samples
  labels:
    app: k8sample
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
  selector:
    app: k8sample