---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8sample
  namespace: k8sample
  labels:
    app: k8sample
spec:
  endpoints:
  - interval: 30s
    port: http
    scheme: http
  namespaceSelector:
    matchNames:
    - k8sample
  selector:
    matchLabels:
      app: k8sample
